name: dart2dserver
description: A sample command-line application
dependencies:
  logging: any
  logging_handlers: any
  route: '>=0.4.6 <0.5.0'
  locking: any
  async: any
dev_dependencies:
  test: '>=0.12.9'
  mockito: any
